# -*- coding: utf-8 -*-
"""UE-FW-4-Methods.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0PhvLDsiVqEx6TP3AdQLf4iDjtB-LFG
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
import pandas as pd
from scipy.optimize import minimize, minimize_scalar
from scipy.integrate import quad  # 引入积分模块
import time

try:
    from IPython.display import display
except ImportError:
    display = print

q = 1.0              # total demand

# FW outer-loop parameters
fw_tol = 1e-4
fw_max_iter = 200

# line-search parameters
eps_ls = 1e-4
alpha_max = 1.0

# define cost functions
def t1(x1):
    return x1

def t2(x2):
    return x2

def t3(x3):
    return x3 + 1.0


# define cost vectors
def C(x):
    return np.array(
        [t1(x[0]), t2(x[1]), t3(x[2])]
    )

# define Beckmann function
def Z(x):
    return 0.5*x[0]**2 + 0.5 * x[1]**2 + 0.5 * x[2] **2 +x[2]

# define AON assignment
def AON(cost):
    y = np.zeros_like(cost)
    shortest_path_index = np.argmin(cost)
    y[shortest_path_index] = q
    return y

'''
x1, x2, x3 = 0, 0, 0
x_free = np.array([x1, x2, x3])
print(x_free)
free_cost = C(x_free)
x = AON(free_cost)
print(free_cost)
print(x)
'''

x1, x2, x3 = 0.2, 0.6, 0.2
x = np.array([x1, x2, x3])
cost = C(x)
y = AON(cost)
d = y - x
print(cost)
print(y)
print(d)

def x_alpha(x, d, alpha):
    return x + alpha * d

print(x_alpha(x, d, 0.0))
print(x_alpha(x, d, 0.5))
print(x_alpha(x, d, 1.0))

def phi(x, d, alpha):
    return Z(x_alpha(x, d, alpha))

print(phi(x, d, 0.0))
print(phi(x, d, 0.5))
print(phi(x, d, 1.0))

def phi_prime(x, d, alpha):
    return np.dot(C(x_alpha(x, d, alpha)), d)

print(phi_prime(x, d, 0.0))
print(phi_prime(x, d, 0.5))
print(phi_prime(x, d, 1.0))

# vibe version for bisection
'''
def line_search_bisection(x, d, eps_ls, a=0.0, b=1.0, line_max_iter=100):
    line_start_time = time.perf_counter()

    left = a
    right = b

    n_ls = 0
    derivative_evals = 0

    # evaluate phi'(left)
    g_left = phi_prime(x, d, left)
    derivative_evals += 1

    if g_left >= 0:
        alpha = left
        line_runtime = time.perf_counter() - line_start_time
        return alpha, n_ls, derivative_evals, line_runtime

    # evaluate phi'(right)
    g_right = phi_prime(x, d, right)
    derivative_evals += 1

    if g_right <= 0:
        alpha = right
        line_runtime = time.perf_counter() - line_start_time
        return alpha, n_ls, derivative_evals, line_runtime

    # bisection interval reduction
    while (right - left) > 2.0 * eps_ls and n_ls < line_max_iter:
        mid = (left + right) / 2.0

        # evaluate phi'(mid) only once
        g_mid = phi_prime(x, d, mid)
        derivative_evals += 1

        if g_mid < 0:
            left = mid
        else:
            right = mid

        n_ls += 1

    alpha = (left + right) / 2.0

    line_runtime = time.perf_counter() - line_start_time

    return alpha, n_ls, derivative_evals, line_runtime
'''

def line_search_bisection(
    x, d, eps_ls,
    a=0.0,
    b=1.0,
    g_left=None,
    g_right=None,
    line_max_iter=100
):
    line_start_time = time.perf_counter()

    left = a
    right = b

    n_ls = 0
    derivative_evals = 0

    # 如果外面没有传入 phi'(left)，这里才计算
    if g_left is None:
        g_left = phi_prime(x, d, left)
        derivative_evals += 1

    # 如果左端点导数已经 >= 0，说明最优点在左边界
    if g_left >= 0:
        alpha = left
        line_runtime = time.perf_counter() - line_start_time
        return alpha, n_ls, derivative_evals, line_runtime

    # 如果外面没有传入 phi'(right)，这里才计算
    if g_right is None:
        g_right = phi_prime(x, d, right)
        derivative_evals += 1

    # 如果右端点导数仍然 <= 0，说明最优点在右边界
    if g_right <= 0:
        alpha = right
        line_runtime = time.perf_counter() - line_start_time
        return alpha, n_ls, derivative_evals, line_runtime

    # 现在应该有：
    # g_left < 0 < g_right
    # 所以最优 alpha 在 [left, right] 内
    while (right - left) > 2.0 * eps_ls and n_ls < line_max_iter:
        mid = (left + right) / 2.0

        g_mid = phi_prime(x, d, mid)
        derivative_evals += 1

        if g_mid < 0:
            left = mid
            g_left = g_mid
        else:
            right = mid
            g_right = g_mid

        n_ls += 1

    alpha = (left + right) / 2.0
    line_runtime = time.perf_counter() - line_start_time

    return alpha, n_ls, derivative_evals, line_runtime

def first_order_adaptive_interval(
    x, d, alpha_prev, alpha_max=1.0, beta=2.0, max_expand=100):
    eps = 1e-12

    c = alpha_prev #previous step size,
    if c <=0.0:
      c = eps
    if c> alpha_max:
      c = alpha_max

    #initial trial interval: a = b = alpha_(n-1)
    a = c
    b = c

    #since a = b, derivation only once
    g = phi_prime(x, d, a)
    ga = g
    gb = g

    interval_derivative_eval = 1
    interval_expansions = 0

    for _ in range(max_expand):
      if ga > 0.0:
        b = a
        gb = ga
        a = max(0.0, a / beta)
        ga = phi_prime(x, d, a)
        interval_derivative_eval += 1
        interval_expansions += 1

      elif gb < 0.0 and b < alpha_max:
        a = b
        ga = gb
        b = min(alpha_max, b * beta)
        gb = phi_prime(x, d, b)
        interval_derivative_eval += 1
        interval_expansions += 1

      else:
        return a, b, ga, gb, interval_expansions, interval_derivative_eval
    return a, b, ga, gb, interval_expansions, interval_derivative_eval

def line_search_adaptive_bisection(
    x,
    d,
    eps_ls,
    alpha_prev,
    alpha_max=1.0,
    beta=2.0,
    line_max_iter=100
):
    line_start_time = time.perf_counter()
    a, b, ga, gb, interval_expansions, interval_derivative_evals = first_order_adaptive_interval(
        x,
        d,
        alpha_prev=alpha_prev,
        alpha_max=alpha_max,
        beta=beta
    ) # fine adaptive interval [a, b]

    alpha, n_ls, bisection_derivative_evals, _ = line_search_bisection(
        x,
        d,
        eps_ls=eps_ls,
        a=a,
        b=b,
        g_left=ga,
        g_right=gb,
        line_max_iter=line_max_iter
    )
    total_derivative_evals = interval_derivative_evals + bisection_derivative_evals
    line_runtime = time.perf_counter() - line_start_time

    return (
        alpha,
        a,
        b,
        ga,
        gb,
        interval_expansions,
        n_ls,
        interval_derivative_evals,
        bisection_derivative_evals,
        total_derivative_evals,
        line_runtime
    )

def line_search_golden(x, d, eps_ls, a=0.0, b=1.0, line_max_iter=100):
    line_start_time = time.perf_counter()

    left = a
    right = b

    n_ls = 0
    function_evals = 0

    # golden section reduction
    r = (np.sqrt(5.0) - 1.0) / 2.0 # 0.618

    alpha1 = right - r * (right - left)
    alpha2 = left + r * (right - left)

    phi1 = phi(x, d, alpha1)
    function_evals += 1
    phi2 = phi(x, d, alpha2)
    function_evals += 1

    while (right - left) > 2.0 * eps_ls and n_ls < line_max_iter:
      if phi1 <= phi2: #最小值在left到alpha2
        right = alpha2
        alpha2 = alpha1
        phi2 = phi1
        alpha1 = right - r * (right - left)  # 更新 alpha1
        phi1 = phi(x, d, alpha1)
        function_evals += 1

      else: #最小值在alpha1到right
        left = alpha1
        alpha1 = alpha2
        phi1 = phi2
        alpha2 = left + r * (right - left)
        phi2 = phi(x, d, alpha2)
        function_evals += 1

      n_ls += 1

    alpha = (left + right) / 2.0

    line_runtime = time.perf_counter() - line_start_time

    return alpha, n_ls, function_evals, line_runtime

def zero_order_adaptive_inteval(x, d, alpha_prev, alpha_max=1.0, beta=2.0, max_expand=100):
    eps = 1e-12

    c = alpha_prev #previous step size,
    # check: keep c inside
    if c <=0.0:
      c = eps
    if c> alpha_max:
      c = alpha_max

    a = max(0.0, c / beta)
    b = min(alpha_max, c * beta)

    phi_a = phi(x, d, a)
    phi_c = phi(x, d, c)
    phi_b = phi(x, d, b)

    interval_function_evals = 3
    interval_expansions = 0

    for _ in range(max_expand):
      if phi_a < phi_c and a > 0.0:
        b, phi_b = c, phi_c
        c, phi_c = a, phi_a
        a = max(0.0, a / beta)
        phi_a = phi(x, d, a)

        interval_function_evals += 1
        interval_expansions += 1

      elif phi_b < phi_c and b < alpha_max:
        a, phi_a = c, phi_c
        c, phi_c = b, phi_b
        b = min(alpha_max, b * beta)
        phi_b = phi(x, d, b)

        interval_function_evals += 1
        interval_expansions += 1

      else:
        return a, b, interval_expansions, interval_function_evals

    return a, b, interval_expansions, interval_function_evals

def line_search_adaptive_golden(x, d, eps_ls, alpha_prev, alpha_max=1.0, beta=2.0, line_max_iter=100):
    line_start_time = time.perf_counter()

    a, b, interval_expansions, interval_evals = zero_order_adaptive_inteval(
        x,
        d,
        alpha_prev=alpha_prev,
        alpha_max=alpha_max,
        beta=beta)

    alpha, n_ls, golden_evals, golden_runtime = line_search_golden(
        x,
        d,
        eps_ls=eps_ls,
        a=a,
        b=b,
        line_max_iter=line_max_iter
    )

    total_function_evals = interval_evals + golden_evals
    line_runtime = time.perf_counter() - line_start_time

    return (
        alpha,
        a,
        b,
        interval_expansions,
        n_ls,
        interval_evals,
        golden_evals,
        total_function_evals,
        line_runtime,
    )

def theoretical_golden_N_ls(eps_ls=1e-4, I0=1.0): #用于检查的代码
    r = (np.sqrt(5.0) - 1.0) / 2.0
    return int(np.ceil(np.log(2.0 * eps_ls / I0) / np.log(r)))

print(theoretical_golden_N_ls(eps_ls=1e-4))

def fw_gap(x, y):
    return np.dot(C(x), x - y)

# vibe coding for recording
def frank_wolfe_bisection(x, fw_tol, fw_max_iter, eps_ls):
    history = []

    total_n_ls = 0
    total_derivative_evals = 0

    total_start_time = time.perf_counter()

    for n in range(fw_max_iter):
        iter_start_time = time.perf_counter()

        cost = C(x)
        y = AON(cost)
        gap = fw_gap(x, y)
        obj = Z(x)

        if gap < fw_tol:
            print("converged at iteration", n)
            break

        d = y - x

        alpha, n_ls, derivative_evals, line_runtime = line_search_bisection(
            x, d, eps_ls=eps_ls
        )

        total_n_ls += n_ls
        total_derivative_evals += derivative_evals

        x_next = x_alpha(x, d, alpha)

        iter_runtime = time.perf_counter() - iter_start_time
        cumulative_runtime = time.perf_counter() - total_start_time

        history.append([
            n,
            x[0], x[1], x[2],
            cost[0], cost[1], cost[2],
            y[0], y[1], y[2],
            d[0], d[1], d[2],
            obj,
            gap,
            alpha,
            n_ls,
            derivative_evals,
            total_n_ls,
            total_derivative_evals,
            line_runtime,
            iter_runtime,
            cumulative_runtime,
            x_next[0], x_next[1], x_next[2]
        ])

        x = x_next

    history = pd.DataFrame(
        history,
        columns=[
            "fw_iter",
            "x1", "x2", "x3",
            "cost1", "cost2", "cost3",
            "y1", "y2", "y3",
            "d1", "d2", "d3",
            "Z",
            "gap",
            "alpha",
            "n_ls",
            "derivative_evals",
            "total_n_ls",
            "total_derivative_evals",
            "line_runtime",
            "iter_runtime",
            "cumulative_runtime",
            "x1_next", "x2_next", "x3_next"
        ]
    )

    return x, history

def frank_wolfe_adaptive_bisection(x, fw_tol, fw_max_iter, eps_ls, beta=2.0):
    history = []

    total_n_ls = 0
    total_interval_derivative_evals = 0
    total_bisection_derivative_evals = 0
    total_derivative_evals = 0

    alpha_prev = 1.0
    total_start_time = time.perf_counter()

    for n in range(fw_max_iter):
      iter_start_time = time.perf_counter()

      cost = C(x)
      y = AON(cost)
      gap = fw_gap(x, y)
      obj = Z(x)

      if gap < fw_tol:
        print("converged at iteration", n)
        break

      d = y - x

      if n == 0:
        alpha, n_ls, bisection_derivative_evals, line_runtime = line_search_bisection(
            x,
            d,
            eps_ls=eps_ls,
            a=0.0,
            b=alpha_max
        )
        interval_a = 0.0
        interval_b = alpha_max
        ga = np.nan
        gb = np.nan
        interval_expansions = 0
        interval_derivative_evals = 0
        total_derivative_evals_this_iter = bisection_derivative_evals

      else:
        (
            alpha,
            interval_a,
            interval_b,
            ga,
            gb,
            interval_expansions,
            n_ls,
            interval_derivative_evals,
            bisection_derivative_evals,
            total_derivative_evals_this_iter,
            line_runtime
        ) = line_search_adaptive_bisection(
            x,
            d,
            eps_ls=eps_ls,
            alpha_prev=alpha_prev,
            alpha_max=alpha_max,
            beta=beta
        )
      total_n_ls += n_ls
      total_interval_derivative_evals += interval_derivative_evals
      total_bisection_derivative_evals += bisection_derivative_evals
      total_derivative_evals += total_derivative_evals_this_iter

      x_next = x_alpha(x, d, alpha)

      iter_runtime = time.perf_counter() - iter_start_time
      cumulative_runtime = time.perf_counter() - total_start_time

      history.append([
          n,
          x[0], x[1], x[2],
          cost[0], cost[1], cost[2],
          y[0], y[1], y[2],
          d[0], d[1], d[2],
          obj,
          gap,
          alpha,
          alpha_prev,
          interval_a,
          interval_b,
          ga,
          gb,
          interval_b - interval_a,
          interval_expansions,
          n_ls,
          interval_derivative_evals,
          bisection_derivative_evals,
          total_derivative_evals_this_iter,
          total_n_ls,
          total_interval_derivative_evals,
          total_bisection_derivative_evals,
          total_derivative_evals,
          line_runtime,
          iter_runtime,
          cumulative_runtime,
          x_next[0], x_next[1], x_next[2]
      ])

      x = x_next
      alpha_prev = max(alpha, 1e-12)

    history = pd.DataFrame(
        history,
        columns=[
            "fw_iter",
            "x1", "x2", "x3",
            "cost1", "cost2", "cost3",
            "y1", "y2", "y3",
            "d1", "d2", "d3",
            "Z",
            "gap",
            "alpha",
            "alpha_prev",
            "interval_a",
            "interval_b",
            "ga",
            "gb",
            "interval_length",
            "interval_expansions",
            "n_ls",
            "interval_derivative_evals",
            "bisection_derivative_evals",
            "derivative_evals",
            "total_n_ls",
            "total_interval_derivative_evals",
            "total_bisection_derivative_evals",
            "total_derivative_evals",
            "line_runtime",
            "iter_runtime",
            "cumulative_runtime",
            "x1_next", "x2_next", "x3_next"
        ]
    )

    return x, history

def frank_wolfe_golden(x, fw_tol, fw_max_iter, eps_ls):
    history = []

    total_n_ls = 0 # golden section缩小区间的次数 interval reductions.
    total_function_evals = 0 # 真正调用phi or phi_prime的次数（包含端点）

    total_start_time = time.perf_counter()

    for n in range(fw_max_iter):
        iter_start_time = time.perf_counter()

        cost = C(x)
        y = AON(cost)
        gap = fw_gap(x, y)
        obj = Z(x)

        if gap < fw_tol:
            print("converged at iteration", n)
            break

        d = y - x

        alpha, n_ls, function_evals, line_runtime = line_search_golden(
            x, d, eps_ls=eps_ls
        )

        total_n_ls += n_ls
        total_function_evals += function_evals

        x_next = x_alpha(x, d, alpha)

        iter_runtime = time.perf_counter() - iter_start_time
        cumulative_runtime = time.perf_counter() - total_start_time

        history.append([
            n,
            x[0], x[1], x[2],
            cost[0], cost[1], cost[2],
            y[0], y[1], y[2],
            d[0], d[1], d[2],
            obj,
            gap,
            alpha,
            n_ls,
            function_evals,
            total_n_ls,
            total_function_evals,
            line_runtime,
            iter_runtime,
            cumulative_runtime,
            x_next[0], x_next[1], x_next[2]
        ])

        x = x_next

    history = pd.DataFrame(
        history,
        columns=[
            "fw_iter",
            "x1", "x2", "x3",
            "cost1", "cost2", "cost3",
            "y1", "y2", "y3",
            "d1", "d2", "d3",
            "Z",
            "gap",
            "alpha",
            "n_ls",
            "function_evals",
            "total_n_ls",
            "total_function_evals",
            "line_runtime",
            "iter_runtime",
            "cumulative_runtime",
            "x1_next", "x2_next", "x3_next"
        ]
    )

    return x, history

def frank_wolfe_adaptive_golden(x, fw_tol, fw_max_iter, eps_ls, beta=2.0):
    history = []

    total_n_ls = 0 # golden section缩小区间的次数 interval reductions.
    total_interval_evals = 0
    total_golden_evals = 0
    total_function_evals = 0 # 真正调用phi or phi_prime的次数（包含端点）

    alpha_prev = 1.0

    total_start_time = time.perf_counter()

    for n in range(fw_max_iter):
        iter_start_time = time.perf_counter()

        cost = C(x)
        y = AON(cost)
        gap = fw_gap(x, y)
        obj = Z(x)

        if gap < fw_tol:
            print("converged at iteration", n)
            break

        d = y - x


        if n == 0:
            alpha, n_ls, golden_evals, line_runtime = line_search_golden(
              x, d, eps_ls=eps_ls, a=0.0, b=alpha_max)

            interval_a = 0.0
            interval_b = alpha_max
            interval_expansions = 0
            interval_evals = 0
            total_function_evals_this_iter = golden_evals

        else:
          (
              alpha,
              interval_a,
              interval_b,
              interval_expansions,
              n_ls,
              interval_evals,
              golden_evals,
              total_function_evals_this_iter,
              line_runtime
          ) = line_search_adaptive_golden(
              x,
              d,
              eps_ls=eps_ls,
              alpha_prev=alpha_prev,
              alpha_max=alpha_max,
              beta=beta
          )

        total_n_ls += n_ls
        total_interval_evals += interval_evals
        total_golden_evals += golden_evals
        total_function_evals += total_function_evals_this_iter

        x_next = x_alpha(x, d, alpha)

        iter_runtime = time.perf_counter() - iter_start_time
        cumulative_runtime = time.perf_counter() - total_start_time

        history.append([
            n,
            x[0], x[1], x[2],
            cost[0], cost[1], cost[2],
            y[0], y[1], y[2],
            d[0], d[1], d[2],
            obj,
            gap,
            alpha,
            alpha_prev,
            interval_a,
            interval_b,
            interval_b - interval_a,
            interval_expansions,
            n_ls,
            interval_evals,
            golden_evals,
            total_function_evals_this_iter,
            total_n_ls,
            total_interval_evals,
            total_golden_evals,
            total_function_evals,
            line_runtime,
            iter_runtime,
            cumulative_runtime,
            x_next[0], x_next[1], x_next[2]
        ])

        x = x_next
        alpha_prev = max(alpha, 1e-12)

    history = pd.DataFrame(
        history,
        columns=[
            "fw_iter",
            "x1", "x2", "x3",
            "cost1", "cost2", "cost3",
            "y1", "y2", "y3",
            "d1", "d2", "d3",
            "Z",
            "gap",
            "alpha",
            "alpha_prev",
            "interval_a",
            "interval_b",
            "interval_length",
            "interval_expansions",
            "n_ls",
            "interval_evals",
            "golden_evals",
            "function_evals",
            "total_n_ls",
            "total_interval_evals",
            "total_golden_evals",
            "total_function_evals",
            "line_runtime",
            "iter_runtime",
            "cumulative_runtime",
            "x1_next", "x2_next", "x3_next"
        ]
    )

    return x, history

# 调用新函数，覆盖旧的 solution 和 history
solution_bisection, history_bisection = frank_wolfe_bisection(
    x, fw_tol, fw_max_iter, eps_ls)

print("Final solution:", solution_bisection)
print("Final cost:", C(solution_bisection))
print("Final objective:", Z(solution_bisection))

display(history_bisection.head())
display(history_bisection.tail())

solution_adaptive_bisection, history_adaptive_bisection = frank_wolfe_adaptive_bisection(
    x,
    fw_tol=fw_tol,
    fw_max_iter=fw_max_iter,
    eps_ls=eps_ls,
    beta=2.0
)

print("Final solution:", solution_adaptive_bisection)
print("Final cost:", C(solution_adaptive_bisection))
print("Final objective:", Z(solution_adaptive_bisection))

display(history_adaptive_bisection.head())
display(history_adaptive_bisection.tail())

display(history_adaptive_bisection[
    [
        "fw_iter",
        "alpha_prev",
        "interval_a",
        "interval_b",
        "ga",
        "gb",
        "interval_length",
        "alpha",
        "n_ls",
        "interval_derivative_evals",
        "bisection_derivative_evals",
        "derivative_evals",
        "total_derivative_evals"
    ]
].head(10))

solution_golden, history_golden = frank_wolfe_golden(
    x, fw_tol=fw_tol, fw_max_iter=fw_max_iter, eps_ls=eps_ls
)

print("Final solution:", solution_golden)
print("Final cost:", C(solution_golden))
print("Final objective:", Z(solution_golden))

display(history_golden.head())
display(history_golden.tail())

solution_adaptive_golden, history_adaptive_golden = frank_wolfe_adaptive_golden(
    x,
    fw_tol=fw_tol,
    fw_max_iter=fw_max_iter,
    eps_ls=eps_ls,
    beta=2.0
)

print("Final solution:", solution_adaptive_golden)
print("Final cost:", C(solution_adaptive_golden))
print("Final objective:", Z(solution_adaptive_golden))

display(history_adaptive_golden.head())
display(history_adaptive_golden.tail())

plt.figure(figsize=(8, 4))
plt.plot(history_golden["fw_iter"], history_golden["function_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Function evaluations per FW iteration")
plt.title("Golden-section function evaluations per FW iteration")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_golden["fw_iter"], history_golden["total_function_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Cumulative function evaluations")
plt.title("Cumulative function evaluations: golden section")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_bisection["fw_iter"], history_bisection["derivative_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Derivative evaluations per FW iteration")
plt.title("Derivative evaluations per FW iteration")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_bisection["fw_iter"], history_bisection["total_derivative_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Cumulative derivative evaluations")
plt.title("Total derivative evaluations")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_bisection["fw_iter"], history_bisection["iter_runtime"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Runtime per FW iteration (seconds)")
plt.title("Runtime per FW iteration for Bisection")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_adaptive_bisection["fw_iter"], history_adaptive_bisection["iter_runtime"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Runtime per FW iteration (seconds)")
plt.title("Runtime per FW iteration for Adaptive Bisection")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_golden["fw_iter"], history_golden["iter_runtime"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Runtime per FW iteration (seconds)")
plt.title("Runtime per FW iteration for Golden Section")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_adaptive_golden["fw_iter"], history_adaptive_golden["iter_runtime"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Runtime per FW iteration (seconds)")
plt.title("Runtime per FW iteration for Adaptive Golden")
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 10))

# feasible region boundary
plt.plot([0, 1, 0, 0], [0, 0, 1, 0], "k-", linewidth=2, label="Feasible region")

# FW trajectory
plt.plot(
    history_bisection["x1"],
    history_bisection["x2"],
    marker="o",
    markersize=4,
    linewidth=1.5,
    label="FW trajectory"
)

# draw zig-zag search directions x^n -> y^n
for i in range(len(history_bisection)):
    x1_now = history_bisection.loc[i, "x1"]
    x2_now = history_bisection.loc[i, "x2"]
    y1_now = history_bisection.loc[i, "y1"]
    y2_now = history_bisection.loc[i, "y2"]

    plt.plot(
        [x1_now, y1_now],
        [x2_now, y2_now],
        linestyle="--",
        alpha=0.35
    )

# mark initial point
plt.scatter([history_bisection.loc[0, "x1"]], [history_bisection.loc[0, "x2"]], s=80, label="Initial point")
plt.text(history_bisection.loc[0, "x1"] + 0.02, history_bisection.loc[0, "x2"], "x0", fontsize=10)

# mark optimal solution
plt.scatter([0.5], [0.5], s=100, marker="*", label="Optimal solution")
plt.text(0.52, 0.50, "x*", fontsize=10)

plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Bisection FW zig-zag behavior")
plt.xlim(-0.05, 1.05)
plt.ylim(-0.05, 1.05)
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(10, 10))

# feasible region boundary
plt.plot([0, 1, 0, 0], [0, 0, 1, 0], "k-", linewidth=2, label="Feasible region")

# FW trajectory
plt.plot(
    history_adaptive_bisection["x1"],
    history_adaptive_bisection["x2"],
    marker="o",
    markersize=4,
    linewidth=1.5,
    label="FW trajectory"
)

# draw zig-zag search directions x^n -> y^n
for i in range(len(history_bisection)):
    x1_now = history_adaptive_bisection.loc[i, "x1"]
    x2_now = history_adaptive_bisection.loc[i, "x2"]
    y1_now = history_adaptive_bisection.loc[i, "y1"]
    y2_now = history_adaptive_bisection.loc[i, "y2"]

    plt.plot(
        [x1_now, y1_now],
        [x2_now, y2_now],
        linestyle="--",
        alpha=0.35
    )

# mark initial point
plt.scatter([history_adaptive_bisection.loc[0, "x1"]], [history_adaptive_bisection.loc[0, "x2"]], s=80, label="Initial point")
plt.text(history_adaptive_bisection.loc[0, "x1"] + 0.02, history_adaptive_bisection.loc[0, "x2"], "x0", fontsize=10)

# mark optimal solution
plt.scatter([0.5], [0.5], s=100, marker="*", label="Optimal solution")
plt.text(0.52, 0.50, "x*", fontsize=10)

plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Adaptive Bisection FW zig-zag behavior")
plt.xlim(-0.05, 1.05)
plt.ylim(-0.05, 1.05)
plt.grid(True)
plt.legend()
plt.show()

def plot_bisection_zoom_overlay(
    history_bisection,
    history_adaptive_bisection,
    start_iter=0,
    end_iter=20,
    show_search_direction=False,
    padding_ratio=0.15,
    figsize=(8, 8)
):
    """
    Overlay fixed bisection and adaptive bisection FW trajectories
    in a zoomed region.

    Parameters
    ----------
    history_bisection:
        history table from fixed bisection

    history_adaptive_bisection:
        history table from adaptive bisection

    start_iter, end_iter:
        iteration range to zoom in

    show_search_direction:
        If True, also draw x^n -> y^n search directions.
        Usually keep False for comparison, otherwise the graph is messy.

    padding_ratio:
        extra margin around the zoomed points

    figsize:
        figure size
    """

    # Make sure both histories have comparable length
    max_len = min(len(history_bisection), len(history_adaptive_bisection))
    end_iter = min(end_iter, max_len - 1)

    fixed = history_bisection.iloc[start_iter:end_iter + 1].copy()
    adaptive = history_adaptive_bisection.iloc[start_iter:end_iter + 1].copy()

    plt.figure(figsize=figsize)

    # feasible region boundary
    plt.plot(
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        "k-",
        linewidth=1.5,
        label="Feasible region"
    )

    # fixed bisection trajectory
    plt.plot(
        fixed["x1"],
        fixed["x2"],
        marker="o",
        markersize=6,
        linewidth=1.8,
        label="Fixed bisection"
    )

    # adaptive bisection trajectory
    plt.plot(
        adaptive["x1"],
        adaptive["x2"],
        marker="x",
        markersize=7,
        linewidth=1.8,
        linestyle="--",
        label="Adaptive bisection"
    )

    # connect points with the same FW iteration
    # This directly shows point-wise difference.
    for idx in range(len(fixed)):
        xf = fixed.iloc[idx]["x1"]
        yf = fixed.iloc[idx]["x2"]

        xa = adaptive.iloc[idx]["x1"]
        ya = adaptive.iloc[idx]["x2"]

        n = int(fixed.iloc[idx]["fw_iter"])

        plt.plot(
            [xf, xa],
            [yf, ya],
            linestyle=":",
            linewidth=1.0,
            alpha=0.6
        )

        # label selected iterations only, otherwise too crowded
        if idx == 0 or idx == len(fixed) - 1 or idx % 5 == 0:
            plt.text(
                xa + 0.001,
                ya + 0.001,
                str(n),
                fontsize=9
            )

    # optionally draw search directions x^n -> y^n
    if show_search_direction:
        for idx in range(len(fixed)):
            plt.plot(
                [fixed.iloc[idx]["x1"], fixed.iloc[idx]["y1"]],
                [fixed.iloc[idx]["x2"], fixed.iloc[idx]["y2"]],
                linestyle="--",
                alpha=0.18
            )

            plt.plot(
                [adaptive.iloc[idx]["x1"], adaptive.iloc[idx]["y1"]],
                [adaptive.iloc[idx]["x2"], adaptive.iloc[idx]["y2"]],
                linestyle=":",
                alpha=0.18
            )

    # optimal solution
    plt.scatter(
        [0.5],
        [0.5],
        s=120,
        marker="*",
        label="Optimal solution"
    )

    # automatic zoom range based on selected points
    all_x = np.concatenate([
        fixed["x1"].to_numpy(),
        adaptive["x1"].to_numpy(),
        np.array([0.5])
    ])

    all_y = np.concatenate([
        fixed["x2"].to_numpy(),
        adaptive["x2"].to_numpy(),
        np.array([0.5])
    ])

    x_min, x_max = all_x.min(), all_x.max()
    y_min, y_max = all_y.min(), all_y.max()

    x_span = max(x_max - x_min, 1e-4)
    y_span = max(y_max - y_min, 1e-4)

    plt.xlim(x_min - padding_ratio * x_span, x_max + padding_ratio * x_span)
    plt.ylim(y_min - padding_ratio * y_span, y_max + padding_ratio * y_span)

    plt.xlabel("x1")
    plt.ylabel("x2")
    plt.title(
        f"Zoomed FW zig-zag: fixed vs adaptive bisection "
        f"(iterations {start_iter}–{end_iter})"
    )
    plt.grid(True)
    plt.legend()
    plt.show()

plot_bisection_zoom_overlay(
    history_bisection,
    history_adaptive_bisection,
    start_iter=0,
    end_iter=20,
    show_search_direction=False,
    figsize=(8, 8)
)

plot_bisection_zoom_overlay(
    history_bisection,
    history_adaptive_bisection,
    start_iter=150,
    end_iter=199,
    show_search_direction=False,
    figsize=(8, 8)
) #这里说明基本看不出端点处的细微区别

# 找两个方法每一轮的点位距离
def compare_bisection_points(history_bisection, history_adaptive_bisection):
    n = min(len(history_bisection), len(history_adaptive_bisection))

    fixed = history_bisection.iloc[:n].reset_index(drop=True)
    adaptive = history_adaptive_bisection.iloc[:n].reset_index(drop=True)

    compare = pd.DataFrame({
        "fw_iter": fixed["fw_iter"],

        "fixed_x1": fixed["x1"],
        "fixed_x2": fixed["x2"],
        "fixed_x3": fixed["x3"],

        "adaptive_x1": adaptive["x1"],
        "adaptive_x2": adaptive["x2"],
        "adaptive_x3": adaptive["x3"],

        "fixed_alpha": fixed["alpha"],
        "adaptive_alpha": adaptive["alpha"],
    })

    compare["dx1"] = compare["adaptive_x1"] - compare["fixed_x1"]
    compare["dx2"] = compare["adaptive_x2"] - compare["fixed_x2"]
    compare["dx3"] = compare["adaptive_x3"] - compare["fixed_x3"]

    compare["point_distance_x1x2"] = np.sqrt(
        compare["dx1"]**2 + compare["dx2"]**2
    )

    compare["point_distance_x123"] = np.sqrt(
        compare["dx1"]**2 + compare["dx2"]**2 + compare["dx3"]**2
    )

    compare["alpha_diff"] = compare["adaptive_alpha"] - compare["fixed_alpha"]

    return compare


compare_bis = compare_bisection_points(
    history_bisection,
    history_adaptive_bisection
)

display(compare_bis.head(10))
display(compare_bis.tail(10))

print("max |dx1|:", compare_bis["dx1"].abs().max())
print("max |dx2|:", compare_bis["dx2"].abs().max())
print("max x1-x2 distance:", compare_bis["point_distance_x1x2"].max())
print("mean x1-x2 distance:", compare_bis["point_distance_x1x2"].mean())
print("max |alpha diff|:", compare_bis["alpha_diff"].abs().max())

# 两个方法每一轮的点位距离
plt.figure(figsize=(9, 4))

plt.plot(
    compare_bis["fw_iter"],
    compare_bis["point_distance_x1x2"],
    marker="o",
    markersize=3,
    linewidth=1.5
)

plt.xlabel("FW iteration")
plt.ylabel("Distance between fixed and adaptive points")
plt.title("Pointwise trajectory difference: fixed vs adaptive bisection")
plt.grid(True)
plt.show()

