# -*- coding: utf-8 -*-
"""UE-FW-Bisection-Golden-Section.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O0PhvLDsiVqEx6TP3AdQLf4iDjtB-LFG
"""

import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
import pandas as pd
from scipy.optimize import minimize, minimize_scalar
from scipy.integrate import quad  # 引入积分模块
import time

try:
    from IPython.display import display
except ImportError:
    display = print

q = 1.0              # total demand

# FW outer-loop parameters
fw_tol = 1e-4
fw_max_iter = 200

# line-search parameters
eps_ls = 1e-4
alpha_max = 1.0

# define cost functions
def t1(x1):
    return x1

def t2(x2):
    return x2

def t3(x3):
    return x3 + 1.0


# define cost vectors
def C(x):
    return np.array(
        [t1(x[0]), t2(x[1]), t3(x[2])]
    )

# define Beckmann function
def Z(x):
    return 0.5*x[0]**2 + 0.5 * x[1]**2 + 0.5 * x[2] **2 +x[2]

# define AON assignment
def AON(cost):
    y = np.zeros_like(cost)
    shortest_path_index = np.argmin(cost)
    y[shortest_path_index] = q
    return y

'''
x1, x2, x3 = 0, 0, 0
x_free = np.array([x1, x2, x3])
print(x_free)
free_cost = C(x_free)
x = AON(free_cost)
print(free_cost)
print(x)
'''

x1, x2, x3 = 0.2, 0.6, 0.2
x = np.array([x1, x2, x3])
cost = C(x)
y = AON(cost)
d = y - x
print(cost)
print(y)
print(d)

def x_alpha(x, d, alpha):
    return x + alpha * d

print(x_alpha(x, d, 0.0))
print(x_alpha(x, d, 0.5))
print(x_alpha(x, d, 1.0))

def phi(x, d, alpha):
    return Z(x_alpha(x, d, alpha))

print(phi(x, d, 0.0))
print(phi(x, d, 0.5))
print(phi(x, d, 1.0))

def phi_prime(x, d, alpha):
    return np.dot(C(x_alpha(x, d, alpha)), d)

print(phi_prime(x, d, 0.0))
print(phi_prime(x, d, 0.5))
print(phi_prime(x, d, 1.0))

# vibe version for bisection
def line_search_bisection(x, d, eps_ls, line_max_iter=100):
    line_start_time = time.perf_counter()

    left = 0.0
    right = 1.0

    n_ls = 0
    derivative_evals = 0

    # evaluate phi'(left)
    g_left = phi_prime(x, d, left)
    derivative_evals += 1

    if g_left >= 0:
        alpha = left
        line_runtime = time.perf_counter() - line_start_time
        return alpha, n_ls, derivative_evals, line_runtime

    # evaluate phi'(right)
    g_right = phi_prime(x, d, right)
    derivative_evals += 1

    if g_right <= 0:
        alpha = right
        line_runtime = time.perf_counter() - line_start_time
        return alpha, n_ls, derivative_evals, line_runtime

    # bisection interval reduction
    while (right - left) > 2.0 * eps_ls and n_ls < line_max_iter:
        mid = (left + right) / 2.0

        # evaluate phi'(mid) only once
        g_mid = phi_prime(x, d, mid)
        derivative_evals += 1

        if g_mid < 0:
            left = mid
        else:
            right = mid

        n_ls += 1

    alpha = (left + right) / 2.0

    line_runtime = time.perf_counter() - line_start_time

    return alpha, n_ls, derivative_evals, line_runtime

def line_search_golden(x, d, eps_ls, line_max_iter=100):
    line_start_time = time.perf_counter()

    left = 0.0
    right = 1.0

    n_ls = 0
    function_evals = 0

    # golden section reduction
    r = (np.sqrt(5.0) - 1.0) / 2.0 # 0.618

    alpha1 = right - r * (right - left)
    alpha2 = left + r * (right - left)

    phi1 = phi(x, d, alpha1)
    function_evals += 1
    phi2 = phi(x, d, alpha2)
    function_evals += 1

    while (right - left) > 2.0 * eps_ls and n_ls < line_max_iter:
      if phi1 <= phi2: #最小值在left到alpha2
        right = alpha2
        alpha2 = alpha1
        phi2 = phi1
        alpha1 = right - r * (right - left)
        phi1 = phi(x, d, alpha1)
        function_evals += 1
      else: #最小值在alpha1到right
        left = alpha1
        alpha1 = alpha2
        phi1 = phi2
        alpha2 = left + r * (right - left)
        phi2 = phi(x, d, alpha2)
        function_evals += 1

      n_ls += 1

    alpha = (left + right) / 2.0

    line_runtime = time.perf_counter() - line_start_time

    return alpha, n_ls, function_evals, line_runtime

def theoretical_golden_N_ls(eps_ls=1e-4, I0=1.0): #用于检查的代码
    r = (np.sqrt(5.0) - 1.0) / 2.0
    return int(np.ceil(np.log(2.0 * eps_ls / I0) / np.log(r)))

print(theoretical_golden_N_ls(eps_ls=1e-4))

def fw_gap(x, y):
    return np.dot(C(x), x - y)

# vibe coding for recording
def frank_wolfe_bisection(x, fw_tol, fw_max_iter, eps_ls):
    history = []

    total_n_ls = 0
    total_derivative_evals = 0

    total_start_time = time.perf_counter()

    for n in range(fw_max_iter):
        iter_start_time = time.perf_counter()

        cost = C(x)
        y = AON(cost)
        gap = fw_gap(x, y)
        obj = Z(x)

        if gap < fw_tol:
            print("converged at iteration", n)
            break

        d = y - x

        alpha, n_ls, derivative_evals, line_runtime = line_search_bisection(
            x, d, eps_ls=eps_ls
        )

        total_n_ls += n_ls
        total_derivative_evals += derivative_evals

        x_next = x_alpha(x, d, alpha)

        iter_runtime = time.perf_counter() - iter_start_time
        cumulative_runtime = time.perf_counter() - total_start_time

        history.append([
            n,
            x[0], x[1], x[2],
            cost[0], cost[1], cost[2],
            y[0], y[1], y[2],
            d[0], d[1], d[2],
            obj,
            gap,
            alpha,
            n_ls,
            derivative_evals,
            total_n_ls,
            total_derivative_evals,
            line_runtime,
            iter_runtime,
            cumulative_runtime,
            x_next[0], x_next[1], x_next[2]
        ])

        x = x_next

    history = pd.DataFrame(
        history,
        columns=[
            "fw_iter",
            "x1", "x2", "x3",
            "cost1", "cost2", "cost3",
            "y1", "y2", "y3",
            "d1", "d2", "d3",
            "Z",
            "gap",
            "alpha",
            "n_ls",
            "derivative_evals",
            "total_n_ls",
            "total_derivative_evals",
            "line_runtime",
            "iter_runtime",
            "cumulative_runtime",
            "x1_next", "x2_next", "x3_next"
        ]
    )

    return x, history

def frank_wolfe_golden(x, fw_tol, fw_max_iter, eps_ls):
    history = []

    total_n_ls = 0 # golden section缩小区间的次数 interval reductions.
    total_function_evals = 0 # 真正调用phi or phi_prime的次数（包含端点）

    total_start_time = time.perf_counter()

    for n in range(fw_max_iter):
        iter_start_time = time.perf_counter()

        cost = C(x)
        y = AON(cost)
        gap = fw_gap(x, y)
        obj = Z(x)

        if gap < fw_tol:
            print("converged at iteration", n)
            break

        d = y - x

        alpha, n_ls, function_evals, line_runtime = line_search_golden(
            x, d, eps_ls=eps_ls
        )

        total_n_ls += n_ls
        total_function_evals += function_evals

        x_next = x_alpha(x, d, alpha)

        iter_runtime = time.perf_counter() - iter_start_time
        cumulative_runtime = time.perf_counter() - total_start_time

        history.append([
            n,
            x[0], x[1], x[2],
            cost[0], cost[1], cost[2],
            y[0], y[1], y[2],
            d[0], d[1], d[2],
            obj,
            gap,
            alpha,
            n_ls,
            function_evals,
            total_n_ls,
            total_function_evals,
            line_runtime,
            iter_runtime,
            cumulative_runtime,
            x_next[0], x_next[1], x_next[2]
        ])

        x = x_next

    history = pd.DataFrame(
        history,
        columns=[
            "fw_iter",
            "x1", "x2", "x3",
            "cost1", "cost2", "cost3",
            "y1", "y2", "y3",
            "d1", "d2", "d3",
            "Z",
            "gap",
            "alpha",
            "n_ls",
            "function_evals",
            "total_n_ls",
            "total_function_evals",
            "line_runtime",
            "iter_runtime",
            "cumulative_runtime",
            "x1_next", "x2_next", "x3_next"
        ]
    )

    return x, history

# 调用新函数，覆盖旧的 solution 和 history
solution_bisection, history_bisection = frank_wolfe_bisection(
    x, fw_tol, fw_max_iter, eps_ls)

print("Final solution:", solution_bisection)
print("Final cost:", C(solution_bisection))
print("Final objective:", Z(solution_bisection))

display(history_bisection.head())
display(history_bisection.tail())

solution_golden, history_golden = frank_wolfe_golden(
    x, fw_tol=fw_tol, fw_max_iter=fw_max_iter, eps_ls=eps_ls
)

print("Final solution:", solution_golden)
print("Final cost:", C(solution_golden))
print("Final objective:", Z(solution_golden))

display(history_golden.head())
display(history_golden.tail())

plt.figure(figsize=(8, 4))
plt.plot(history_golden["fw_iter"], history_golden["function_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Function evaluations per FW iteration")
plt.title("Golden-section function evaluations per FW iteration")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_golden["fw_iter"], history_golden["total_function_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Cumulative function evaluations")
plt.title("Cumulative function evaluations: golden section")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_bisection["fw_iter"], history_bisection["derivative_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Derivative evaluations per FW iteration")
plt.title("Derivative evaluations per FW iteration")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_bisection["fw_iter"], history_bisection["total_derivative_evals"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Cumulative derivative evaluations")
plt.title("Total derivative evaluations")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_bisection["fw_iter"], history_bisection["iter_runtime"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Runtime per FW iteration (seconds)")
plt.title("Runtime per FW iteration for Bisection")
plt.grid(True)
plt.show()

plt.figure(figsize=(8, 4))
plt.plot(history_golden["fw_iter"], history_golden["iter_runtime"], marker="o")
plt.xlabel("FW iteration n")
plt.ylabel("Runtime per FW iteration (seconds)")
plt.title("Runtime per FW iteration for Golden Section")
plt.grid(True)
plt.show()

plt.figure(figsize=(6, 6))

# feasible region boundary: x1 >= 0, x2 >= 0, x1 + x2 <= 1
triangle_x = [0, 1, 0, 0]
triangle_y = [0, 0, 1, 0]

plt.plot(triangle_x, triangle_y, "k-", linewidth=2, label="Feasible region")

# mark three vertices
plt.scatter([1, 0, 0], [0, 1, 0], s=60)
plt.text(1.02, 0.00, "(1,0,0)", fontsize=10)
plt.text(0.02, 1.02, "(0,1,0)", fontsize=10)
plt.text(0.02, 0.02, "(0,0,1)", fontsize=10)

# mark optimal solution
plt.scatter([0.5], [0.5], s=80, marker="*", label="Optimal solution")
plt.text(0.52, 0.50, "(0.5,0.5,0)", fontsize=10)

plt.xlabel("x1")
plt.ylabel("x2")
plt.title("Feasible region")
plt.xlim(-0.05, 1.08)
plt.ylim(-0.05, 1.08)
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(6, 6))

# feasible region
plt.plot([0, 1, 0, 0], [0, 0, 1, 0], "k-", linewidth=2, label="Feasible region")

# FW trajectory
plt.plot(
    history_bisection["x1"],
    history_bisection["x2"],
    marker="o",
    markersize=4,
    linewidth=1.5,
    label="FW trajectory"
)

# initial point
plt.scatter([history_bisection.loc[0, "x1"]], [history_bisection.loc[0, "x2"]], s=80, label="Initial point")
plt.text(history_bisection.loc[0, "x1"] + 0.02, history_bisection.loc[0, "x2"], "x0", fontsize=10)

# optimal point
plt.scatter([0.5], [0.5], s=100, marker="*", label="Optimal solution")
plt.text(0.52, 0.50, "x*", fontsize=10)

plt.xlabel("x1")
plt.ylabel("x2")
plt.title("FW trajectory in feasible region")
plt.xlim(-0.05, 1.05)
plt.ylim(-0.05, 1.05)
plt.grid(True)
plt.legend()
plt.show()

plt.figure(figsize=(7, 7))

# feasible region boundary
plt.plot([0, 1, 0, 0], [0, 0, 1, 0], "k-", linewidth=2, label="Feasible region")

# FW trajectory
plt.plot(
    history_bisection["x1"],
    history_bisection["x2"],
    marker="o",
    markersize=4,
    linewidth=1.5,
    label="FW trajectory"
)

# draw zig-zag search directions x^n -> y^n
for i in range(len(history_bisection)):
    x1_now = history_bisection.loc[i, "x1"]
    x2_now = history_bisection.loc[i, "x2"]
    y1_now = history_bisection.loc[i, "y1"]
    y2_now = history_bisection.loc[i, "y2"]

    plt.plot(
        [x1_now, y1_now],
        [x2_now, y2_now],
        linestyle="--",
        alpha=0.35
    )

# mark initial point
plt.scatter([history_bisection.loc[0, "x1"]], [history_bisection.loc[0, "x2"]], s=80, label="Initial point")
plt.text(history_bisection.loc[0, "x1"] + 0.02, history_bisection.loc[0, "x2"], "x0", fontsize=10)

# mark optimal solution
plt.scatter([0.5], [0.5], s=100, marker="*", label="Optimal solution")
plt.text(0.52, 0.50, "x*", fontsize=10)

plt.xlabel("x1")
plt.ylabel("x2")
plt.title("FW zig-zag behavior")
plt.xlim(-0.05, 1.05)
plt.ylim(-0.05, 1.05)
plt.grid(True)
plt.legend()
plt.show()

